include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [lib/**/*.g.dart]

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - empty_constructor_bodies
    - empty_catches
    - exhaustive_cases
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_final_in_for_each
    - prefer_final_locals
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_this
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - library_names
    - non_constant_identifier_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps