name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  json_annotation: ^3.1.1

  # http
  dio: ^3.0.10
  connectivity: ^2.0.2

  # service locator
  get_it: ^5.0.4
  dartz: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:
