name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 2.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3

  json_annotation: ^4.7.0
  intl: ^0.17.0

  devicelocale: ^0.5.5

  # http
  dio: ^4.0.6
  connectivity_plus: ^2.3.8

  # service locator
  get_it: ^7.2.0
  injectable: ^1.5.3
  fpdart: ^0.2.0

  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  injectable_generator: ^1.5.4

  flutter_lints: ^2.0.1
