name: clean_architecture_core
description: The core of all flutter project
version: 1.0.0
author:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  json_annotation: ^4.8.0
  equatable: ^2.0.5

  # http
  dio: ^5.1.1
  connectivity: ^3.0.6

  # service locator
  get_it: ^7.2.0
  dartz: ^0.10.1

  # notifications
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  pedantic: ^1.11.1

flutter:
