name: flutter_core
description: The core of all flutter project
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  json_annotation: ^3.1.1

  # http
  dio: ^3.0.10
  connectivity: ^2.0.2
  logger: ^0.9.4

  # service locator
  get_it: ^5.0.6
  dartz: ^0.9.2

  # notifications
  firebase_core: any
  firebase_messaging: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.0
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

flutter:
