name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 2.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1

  json_annotation: ^4.8.0
  intl: ^0.18.1

  devicelocale: ^0.6.0

  # http
  dio: ^5.1.1
  connectivity_plus: ^3.0.4

  # service locator
  get_it: ^7.2.0
  injectable: ^2.1.1
  fpdart: ^0.5.0

  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  injectable_generator: ^2.1.5

  flutter_lints: ^2.0.1
