name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <2.1.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: any
  intl: any

  # http
  dio: any
  connectivity: any

  # service locator
  get_it: any
  dartz: any

  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: any

flutter:
