name: flutter_core
description: The core of all flutter project
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0

  # http
  dio: ^3.0.9
  data_connection_checker: ^0.3.4
  logger: ^0.9.2
  json_serializable: ^3.3.0

  # service locator
  get_it: ^4.0.4

  dartz: ^0.9.1

  # notifications
  firebase_core: ^0.4.5
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  pedantic: ^1.9.0

flutter:
