name: flutter_core
description: The core of all flutter project
version: 1.0.0
author: Camillo Bucciarelli

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  json_annotation: ^3.1.1
  equatable: ^1.2.5

  # http
  dio: ^3.0.10
  connectivity: ^2.0.2

  # service locator
  get_it: ^5.0.3
  dartz: ^0.9.2

  # notifications
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  mockito: ^4.1.3

flutter:
