name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy: ^2.0.1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3

  json_annotation: ^4.1.0
  intl: ^0.17.0

  devicelocale: ^0.4.3

  # http
  dio: ^4.0.0
  connectivity_plus: ^1.1.0

  # service locator
  get_it: ^7.2.0
  fpdart: ^0.0.11

  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
