name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy: ^2.0.1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3

  json_annotation:
  intl:
  devicelocale:

  # http
  dio:
  connectivity_plus:

  # service locator
  get_it:
  fpdart:

  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
