name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: '>=3.1.1 <=4.0.0'

  # http
  dio: ^4.0.0-beta2
  connectivity: ^3.0.0

  # service locator
  get_it: '>=5.0.6 <=6.0.0'
  dartz: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: '>=1.9.2 <=1.10.0'

flutter:
