name: flutter_core
description: The core of all flutter project
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  json_annotation: ^3.1.0

  # http
  dio: ^3.0.10
  data_connection_checker: ^0.3.4
  logger: ^0.9.2

  # service locator
  get_it: ^5.0.1
  dartz: ^0.9.1

  # notifications
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^1.4.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.4.1
  pedantic: ^1.9.0

flutter:
