name: flutter_core
description: The core of all flutter project
version: 0.0.1
author:

environment:
  sdk: ">=2.10.0-0.0.dev <3.0.0"
  flutter: ">=1.22.0-12.1.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  json_annotation: ^3.1.0

  # http
  dio: ^3.0.10
  connectivity: ^0.4.9+3
  logger: ^0.9.3

  # service locator
  get_it: ^5.0.1
  dartz: ^0.9.1

  # notifications
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  pedantic: ^1.9.2

flutter:
