name: clean_architecture_core
description: The core of all clean architecture flutter projects
version: 1.0.0

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation:
  intl:
  devicelocale:

  # http
  dio:
  connectivity:

  # service locator
  get_it:
  fpdart:

  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:
